name: test

on:
  push:
    branches: [master]
  pull_request:
    branches:
      - master

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: print hello
        run: echo 'Hello world!'